apiVersion: v1
kind: Namespace
metadata:
  name: health-check
  labels:
    name: health-check
---
apiVersion: v1
kind: Secret
metadata:
  name: hc-client-secrets
  namespace: health-check
stringData:
  APIVERSION: v4
  TOKEN: UPERSECRET 
  LOCATION:
  MAINDB_PASSWORD:
  MAINDB_HOSTPORT:
  LOCALDB_PASSWORD:
  LOCALDB_HOSTPORT:

